### ISSUE TITLE
Gmail account not able to access from one region to another region even 2FA is disabled ? 

### ISSUE THREAD

**Issue by rajeshjill** [transitive-bullshit/chatgpt-api#230] opened 2023-01-04 09:33 UTC
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

**Node version** : > 18
**Linux version** : 20
**server: google** cloud
**chatgpt version:** latest

### Describe the Bug

Not able to work chatgpt in deployment server. It's asking for verification, but within verification, the authenticate session got expired.

the face below error +1

Thu, 2 Jan 2023 07:28:10 GMT [ERROR] [error] **ChatGPTError: Failed to authenticate session**

In local docker container is working **fine.**

is it **ChatGPTAPIBrowser** that only can access the same region Gmail account?

let me know how to handle this.

**Comment by laosuan** [comment] 2023-01-05 02:58
same issue

**Comment by transitive-bullshit** [comment] 2023-01-05 06:55
Data center IP addresses are viewed by Cloudflare as more risky, so something that may work fine locally will run into more IP-related Cloudflare issues when deployed to any of the major cloud providers including AWS, GCP, and Azure.

To get around this, you need to use a residential proxy or not deploy your program to a cloud provider.

**Comment by cheesebellies** [comment] 2023-01-06 13:38
What do you mean? On Replit?
(if so, yes.)

**Comment by anotherso1a** [comment] 2023-01-09 04:14
same issue. proxyServer on MacOS is working, but cannot run on cloud linux server

**Comment by anotherso1a** [comment] 2023-01-09 08:03
this reappeared on MacOS, maybe cause by google verify
<img width="818" alt="image" src="https://user-images.githubusercontent.com/38176179/211263133-8c9b0153-01ce-4e32-92c3-4b6614cca0c6.png">

But how could I skip this on remote server ?

**Comment by transitive-bullshit** [comment] 2023-01-10 10:42
This may be a duplicate of https://github.com/transitive-bullshit/chatgpt-api/issues/169

**Comment by transitive-bullshit** [comment] 2023-02-01 12:19
Try upgrading to the latest version; we're now using the official API (no puppeteer!) so this should no longer be an issue: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.0.0

**Closed by transitive-bullshit** 2023-02-01 12:19 UTC
