### ISSUE TITLE
Error: Invalid environment; fetch is not defined

### ISSUE THREAD

**Issue by liyang9331** [transitive-bullshit/chatgpt-api#379] opened 2023-02-21 08:19 UTC
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

I use it in nestjs. The nodejs version is not 18. An error is reported when running

### Describe the Bug

I use it in nestjs. The nodejs version is not 18. An error is reported when running

**Comment by Musharaf13** [comment] 2023-02-21 08:25
you might need to update it to node 18.
if you are integrating with the existing project. It will be a challenge but will get eventually done.

**Comment by liyang9331** [comment] 2023-02-21 08:30
> you might need to update it to node 18. if you are integrating with the existing project. It will be a challenge but will get eventually done.

I have used nvm to switch to node18

**Comment by transitive-bullshit** [comment] 2023-02-21 08:44
The readme gives instructions for this; if you're using node < 18, you need to install a `fetch` polyfill. If you're using node >= 18, `fetch` is installed by default.

Closing as a duplicate of https://github.com/transitive-bullshit/chatgpt-api/issues/376

**Closed by transitive-bullshit** 2023-02-21 08:44 UTC

**Comment by lmzacarias** [comment] 2023-07-23 01:56
I have used nvm to switch to node18
