### ISSUE TITLE
fetch failed

### ISSUE THREAD

**Issue by RareSkye** [transitive-bullshit/chatgpt-api#513] opened 2023-03-31 11:01 UTC
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

windows 11
node js 18.15

### Describe the Bug

Everything has always worked correctly, today it gives the same error all day
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchSSE (file:///C:/Users/Andrey/Desktop/gpt/node_modules/chatgpt/build/index.js:46:15) {
  cause: Error: connect ECONNREFUSED 127.0.0.1:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 443
  }
}

**Comment by sam-hieken** [comment] 2023-03-31 22:11
Same here, looks like [something's wrong with the reverse proxy](https://github.com/transitive-bullshit/chatgpt-api/issues/516).

**Comment by transitive-bullshit** [comment] 2023-04-02 17:22
closing as a duplicate of #419 

also, I strongly recommend using the official API via `ChatGPTAPI` going forwards. The unofficial API proxies are not robust and will continue to have intermittent issues.

**Closed by transitive-bullshit** 2023-04-02 17:22 UTC

**Comment by RareSkye** [comment] 2023-04-02 19:04
How can i use official chatGPT? If he demands 5 bucks for a couple of texts. It's easier to turn to russian copywriters

**Comment by transitive-bullshit** [comment] 2023-04-02 19:43
@RareSkye OpenAI API pricing is actually really cheap. you can use `gpt-3.5-turbo` for fractions of a penny per thousand tokens. Details here: https://twitter.com/transitive_bs/status/1635712260424478720
