### ISSUE TITLE
ChatGPT error 503

### ISSUE THREAD

**Issue by hafidzaini** [transitive-bullshit/chatgpt-api#313] opened 2023-02-08 09:32 UTC
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

node 18

### Describe the Bug

anyboy having the same error today?
yesterday was working fine.
shold we change APIkey or use different user api solve this problem? 🤔

Error: ChatGPT error 503: {
  "error": {
    "message": "That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID c5a7aedfb341afd21e5e96e92e9ffc91 in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

**Comment by transitive-bullshit** [comment] 2023-02-08 09:34
OpenAI is blocking the model.

Upgrade to https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v4.2.0 to use `text-davinci-003`. Note this is a paid model and is not fine-tuned for text. We're working on a workaround.

Closing as a dupe of #311

**Closed by transitive-bullshit** 2023-02-08 09:34 UTC

**Comment by Songkeys** [comment] 2023-02-08 11:48
I'd suggest we make that modal field an enum to avoid cutting release frequently just for these unstable changes.

**Comment by transitive-bullshit** [comment] 2023-02-08 20:51
@Songkeys you can override the modal via `completionParams: { modal: 'xxx' }` param to the constructor.

These releases are just updating the default and hopefully it won't change as much in the future.
