### ISSUE TITLE
Is there a plan to support Azure OpenAI?

### ISSUE THREAD

**Issue by stulzq** [transitive-bullshit/chatgpt-api#492] opened 2023-03-23 12:00 UTC
### Describe the feature

Api Doc：https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&pivots=rest-api

**Comment by transitive-bullshit** [comment] 2023-03-28 03:15
Yes, this is planned.

Closing as a duplicate of https://github.com/transitive-bullshit/chatgpt-api/issues/352

**Closed by transitive-bullshit** 2023-03-28 03:15 UTC
