### ISSUE TITLE
getting 403 for Version 2.3.0 

### ISSUE THREAD

**Issue by AlphaCharry** [transitive-bullshit/chatgpt-api#130] opened 2022-12-14 01:17 UTC
(node:91420) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///E:/FontEnd/test/node_modules/chatgpt/build/index.js:350
      const error = new ChatGPTError(
                    ^

ChatGPTError: ChatGPT failed to refresh auth token. Error: 403 Forbidden
    at ChatGPTAPI.refreshAccessToken (file:///E:/FontEnd/test/node_modules/chatgpt/build/index.js:350:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTAPI.ensureAuth (file:///E:/FontEnd/test/node_modules/chatgpt/build/index.js:286:12)
    at async example (file:///E:/FontEnd/test/index.js:17:3) {
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 403,
      timingInfo: {
        startTime: 26534.646200060844,
        redirectStartTime: 0,
        redirectEndTime: 0,
        postRedirectStartTime: 26534.646200060844,
        finalServiceWorkerStartTime: 0,
        finalNetworkResponseStartTime: 0,
        finalNetworkRequestStartTime: 0,
        endTime: 0,
        encodedBodySize: 292,
        decodedBodySize: 0,
        finalConnectionTimingInfo: null
      },
      cacheState: '',
      statusText: 'Forbidden',
      headersList: HeadersList {
        [Symbol(headers map)]: Map(16) {
          'date' => 'Wed, 14 Dec 2022 01:09:08 GMT',
          'content-type' => 'text/html; charset=UTF-8',
          'transfer-encoding' => 'chunked',
          'connection' => 'close',
          'cf-chl-bypass' => '1',
          'permissions-policy' => 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
          'referrer-policy' => 'same-origin',
          'x-frame-options' => 'SAMEORIGIN',
          'cache-control' => 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
          'expires' => 'Thu, 01 Jan 1970 00:00:01 GMT',
          'set-cookie' => '__cf_bm=5M3AwjmFAESkpZxpatuAcLemxcDlaomNJXti5z._rDs-1670980148-0-AarCsASV12DXH5QizVW7xH6EUS1JVKN8ffg5Bj9x3nSn5hpZ0KUmVFW7q4Qvh6Eiuhw18eTPFnPAW7jLyxHLEqw=; path=/; expires=Wed, 14-Dec-22 01:39:08 GMT; domain=.chat.openai.com; HttpOnly; Secure; SameSite=None',
          'vary' => 'Accept-Encoding',
          'server' => 'cloudflare',
          'cf-ray' => '77930d69d8ea27ad-SEA',
          'content-encoding' => 'gzip',
          'alt-svc' => 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
        },
        [Symbol(headers map sorted)]: null
      },
      urlList: [
        <ref *1> URL {
          [Symbol(context)]: URLContext {
            flags: 400,
            scheme: 'https:',
            username: '',
            password: '',
            host: 'chat.openai.com',
            port: null,
            path: [Array],
            query: null,
            fragment: null
          },
          [Symbol(query)]: URLSearchParams {
            [Symbol(query)]: [],
            [Symbol(context)]: [Circular *1]
          }
        }
      ],
      body: {
        stream: ReadableStream {
          [Symbol(kType)]: 'ReadableStream',
          [Symbol(kState)]: {
            disturbed: false,
            reader: undefined,
            state: 'readable',
            storedError: undefined,
            stream: undefined,
            transfer: [Object],
            controller: [ReadableStreamDefaultController]
          }
        }
      }
    },
    [Symbol(headers)]: Headers {
      [Symbol(headers list)]: HeadersList {
        [Symbol(headers map)]: Map(16) {
          'date' => 'Wed, 14 Dec 2022 01:09:08 GMT',
          'content-type' => 'text/html; charset=UTF-8',
          'transfer-encoding' => 'chunked',
          'connection' => 'close',
          'cf-chl-bypass' => '1',
          'permissions-policy' => 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
          'referrer-policy' => 'same-origin',
          'x-frame-options' => 'SAMEORIGIN',
          'cache-control' => 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
          'expires' => 'Thu, 01 Jan 1970 00:00:01 GMT',
          'set-cookie' => '__cf_bm=5M3AwjmFAESkpZxpatuAcLemxcDlaomNJXti5z._rDs-1670980148-0-AarCsASV12DXH5QizVW7xH6EUS1JVKN8ffg5Bj9x3nSn5hpZ0KUmVFW7q4Qvh6Eiuhw18eTPFnPAW7jLyxHLEqw=; path=/; expires=Wed, 14-Dec-22 01:39:08 GMT; domain=.chat.openai.com; HttpOnly; Secure; SameSite=None',
          'vary' => 'Accept-Encoding',
          'server' => 'cloudflare',
          'cf-ray' => '77930d69d8ea27ad-SEA',
          'content-encoding' => 'gzip',
          'alt-svc' => 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
        },
        [Symbol(headers map sorted)]: null
      },
      [Symbol(guard)]: 'immutable',
      [Symbol(realm)]: null
    }
  },
  statusCode: 403,
  statusText: 'Forbidden',
  originalError: ChatGPTError: 403 Forbidden
      at file:///E:/FontEnd/test/node_modules/chatgpt/build/index.js:309:25
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async ChatGPTAPI.refreshAccessToken (file:///E:/FontEnd/test/node_modules/chatgpt/build/index.js:304:19)
      at async ChatGPTAPI.ensureAuth (file:///E:/FontEnd/test/node_modules/chatgpt/build/index.js:286:12)
      at async example (file:///E:/FontEnd/test/index.js:17:3) {
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: {
        aborted: false,
        rangeRequested: false,
        timingAllowPassed: true,
        requestIncludesCredentials: true,
        type: 'default',
        status: 403,
        timingInfo: {
          startTime: 26534.646200060844,
          redirectStartTime: 0,
          redirectEndTime: 0,
          postRedirectStartTime: 26534.646200060844,
          finalServiceWorkerStartTime: 0,
          finalNetworkResponseStartTime: 0,
          finalNetworkRequestStartTime: 0,
          endTime: 0,
          encodedBodySize: 292,
          decodedBodySize: 0,
          finalConnectionTimingInfo: null
        },
        cacheState: '',
        statusText: 'Forbidden',
        headersList: HeadersList {
          [Symbol(headers map)]: Map(16) {
            'date' => 'Wed, 14 Dec 2022 01:09:08 GMT',
            'content-type' => 'text/html; charset=UTF-8',
            'transfer-encoding' => 'chunked',
            'connection' => 'close',
            'cf-chl-bypass' => '1',
            'permissions-policy' => 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
            'referrer-policy' => 'same-origin',
            'x-frame-options' => 'SAMEORIGIN',
            'cache-control' => 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
            'expires' => 'Thu, 01 Jan 1970 00:00:01 GMT',
            'set-cookie' => '__cf_bm=5M3AwjmFAESkpZxpatuAcLemxcDlaomNJXti5z._rDs-1670980148-0-AarCsASV12DXH5QizVW7xH6EUS1JVKN8ffg5Bj9x3nSn5hpZ0KUmVFW7q4Qvh6Eiuhw18eTPFnPAW7jLyxHLEqw=; path=/; expires=Wed, 14-Dec-22 01:39:08 GMT; domain=.chat.openai.com; HttpOnly; Secure; SameSite=None',
            'vary' => 'Accept-Encoding',
            'server' => 'cloudflare',
            'cf-ray' => '77930d69d8ea27ad-SEA',
            'content-encoding' => 'gzip',
            'alt-svc' => 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
          },
          [Symbol(headers map sorted)]: null
        },
        urlList: [
          <ref *1> URL {
            [Symbol(context)]: [URLContext],
            [Symbol(query)]: [URLSearchParams]
          }
        ],
        body: {
          stream: ReadableStream {
            [Symbol(kType)]: 'ReadableStream',
            [Symbol(kState)]: [Object]
          }
        }
      },
      [Symbol(headers)]: Headers {
        [Symbol(headers list)]: HeadersList {
          [Symbol(headers map)]: Map(16) {
            'date' => 'Wed, 14 Dec 2022 01:09:08 GMT',
            'content-type' => 'text/html; charset=UTF-8',
            'transfer-encoding' => 'chunked',
            'connection' => 'close',
            'cf-chl-bypass' => '1',
            'permissions-policy' => 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
            'referrer-policy' => 'same-origin',
            'x-frame-options' => 'SAMEORIGIN',
            'cache-control' => 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
            'expires' => 'Thu, 01 Jan 1970 00:00:01 GMT',
            'set-cookie' => '__cf_bm=5M3AwjmFAESkpZxpatuAcLemxcDlaomNJXti5z._rDs-1670980148-0-AarCsASV12DXH5QizVW7xH6EUS1JVKN8ffg5Bj9x3nSn5hpZ0KUmVFW7q4Qvh6Eiuhw18eTPFnPAW7jLyxHLEqw=; path=/; expires=Wed, 14-Dec-22 01:39:08 GMT; domain=.chat.openai.com; HttpOnly; Secure; SameSite=None',
            'vary' => 'Accept-Encoding',
            'server' => 'cloudflare',
            'cf-ray' => '77930d69d8ea27ad-SEA',
            'content-encoding' => 'gzip',
            'alt-svc' => 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
          },
          [Symbol(headers map sorted)]: null
        },
        [Symbol(guard)]: 'immutable',
        [Symbol(realm)]: null
      }
    },
    statusCode: 403,
    statusText: 'Forbidden'
  }
}

**Comment by transitive-bullshit** [comment] 2022-12-14 01:25
Please double check the `restrictions` section of the readme and also this post: https://github.com/transitive-bullshit/chatgpt-api/issues/107#issuecomment-1346709003

Unfortunately it's not possible to guarantee access like it was in previous versions due to OpenAI's new Cloudflare protections. It is, however, working for many people; you just have to do a little more work.

Closing this as a duplicate of several other issues with very similar topics.

**Closed by transitive-bullshit** 2022-12-14 01:25 UTC

**Comment by AlphaCharry** [comment] 2022-12-14 01:26
No I'm using the latest 2.3 version

**Comment by AlphaCharry** [comment] 2022-12-14 01:36
> Please double check the `restrictions` section of the readme and also this post: [#107 (comment)](https://github.com/transitive-bullshit/chatgpt-api/issues/107#issuecomment-1346709003)
> 
> Unfortunately it's not possible to guarantee access like it was in previous versions due to OpenAI's new Cloudflare protections. It is, however, working for many people; you just have to do a little more work.
> 
> Closing this as a duplicate of several other issues with very similar topics.

I tried this advice with a different browser and still got error 403!
