### ISSUE TITLE
ERROR in ./node_modules/@dqbd/tiktoken/tiktoken_bg.wasm 1:0

### ISSUE THREAD

**Issue by FrancescoMussi** [transitive-bullshit/chatgpt-api#502] opened 2023-03-27 15:00 UTC
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node v16.16.0

### Describe the Bug

Just installed the library inside my Vue3 project.

Right away I am getting the following error:

`ERROR in ./node_modules/@dqbd/tiktoken/tiktoken_bg.wasm 1:0`

Do you know why?

<img width="1744" alt="Screenshot 2023-03-27 at 17 57 49" src="https://user-images.githubusercontent.com/5312907/227979772-aa13a65b-a3d8-49fa-85bf-cc3d2f3e060d.png">

**Comment by lh2731164534** [comment] 2023-03-31 08:10
Have you solved it now? How did you solve it

**Comment by FrancescoMussi** [comment] 2023-03-31 09:50
Actually I think the reason is that this package is not meant to be run by the browser but in a nodeJS environment

**Comment by lh2731164534** [comment] 2023-03-31 16:50
This way, but the writing is not very similar

**Comment by jorge-vnarvaez** [comment] 2023-04-21 17:54
Did you solve it? this error also appears in nodejs enviroment

**Comment by FrancescoMussi** [comment] 2023-04-22 17:25
ah thanks for the info. I didn't know it happens in nodejs env too.
I will reopen the issue

**Comment by transitive-bullshit** [comment] 2023-05-02 03:01
Hmmm going to close this for now since I can't seem to reproduce the issue.

See also https://github.com/dqbd/tiktoken which is the underlying dependency.

If anyone has a reproducible version of this on a specific version of Node.js, please re-open a new issue with more details.

Note that this library is _not_ meant to be run from client-side Vue.js code. It is Node.js only.

**Closed by transitive-bullshit** 2023-05-02 03:01 UTC

**Comment by buenaSopa** [comment] 2023-05-12 07:12
@FrancescoMussi hi, im kinda new to this, did you solve the issue, im using next js and is giving the same issue

**Comment by FrancescoMussi** [comment] 2023-05-12 08:55
No sorry I didn't fix it, I resort using python for connecting to api
