### ISSUE TITLE
The demo of reverse proxy contains malware HTTP service

### ISSUE THREAD

**Issue by davideuler** [transitive-bullshit/chatgpt-api#332] opened 2023-02-14 05:22 UTC
### Verify latest release

- [X] I verified that the issue exists in the latest `chatgpt` release

### Verify webapp is working

- [X] I verify that the ChatGPT webapp is working properly for this account.

### Environment details

Node.js 18.14

Latest version of chatgpt-api.

### Describe the Bug

I tested the demo-reverse-proxy.ts with my ChatGPT paid access token. And I changed the debug to true. 
Soon I've found there is lots of unrelated messages sent to ChatGPT through my accessToken.

I believe the reverse proxy URL in the demo program have made use or leaked my access token.

Related code:
https://github.com/transitive-bullshit/chatgpt-api/pull/327

The original author said the access token would not be used by others, it is not the fact.
https://gist.github.com/PawanOsman/be803be44caed2449927860956b240ad

I think the demo program should not include the reverse proxy address.

Thanks for the chatgpt-api project, its really helpful.

**Comment by transitive-bullshit** [comment] 2023-02-14 06:02
Hey @davideuler, that's really troubling, and thank you for bringing it to my attention.

I have previously messaged with the author of the reverse proxy, and I didn't find any indication of ill intent, but obviously the proxy server is closed source, and there's no way to know for sure.

I will remove the current proxy server URL out of an abundance of caution, since this is definitely not intended behavior.

| Soon I've found there is lots of unrelated messages sent to ChatGPT through my accessToken.

@davideuler would you mind including one or more screenshots of how you were able to determine this? To my knowledge, since the reverse proxy isn't using the official ChatGPT API or the official OpenAI completions API, there should be no way to determine this. I just want to understand and diagnose what's going on before I make any judgements.

Thanks 🙏

**Comment by transitive-bullshit** [comment] 2023-02-14 06:19
Update: removed the proxy server URL from the demo; https://github.com/transitive-bullshit/chatgpt-api/commit/d621fb7c45eb06704fa404eab3c861f2633a3e77

**Comment by davideuler** [comment] 2023-02-14 06:39
Steps I took to find the unexpected behavior.

1.Login to chat.openai.com by ChatGPT plus account, get the access token from the browser.

2.paste the access token to .env file, as 
```
OPENAI_ACCESS_TOKEN=xxxx
```

3.Changed the first promt to my question. I want to check if it returned the same response as the website of chat.openai.com.

4.Run the program by npx.
```
npx tsx demo-reverse-proxy.ts
```

5.It runs several prompts to the server. And I can't check the response for my first prompt. So I added a line to stop the left process of the program after the second prompt at line 53.
```
process.exit(1)
```

6..Run the program again. 
```
npx tsx demo-reverse-proxy.ts
```

I then I see lots of unrelated prompt in my context. Both English and Chinese prompts which is not sent from my host.
The api is in debug mode in default. It shows the message context sent to ChatGPT.
```
    "chatgpt": "^4.3.2",
    "chatgpt-api": "^0.0.6",
```
And I am astonished. I can't believe it, so I tried it one again, and then I see other unexpected messages in the context.

Here is one the screenshots. The other prompt beside "Can you make it cuter and shorter" was not sent from my host.
![image](https://user-images.githubusercontent.com/377983/218658550-48677477-5e44-4e0b-bf1e-13610a8f09d0.png)

**Comment by transitive-bullshit** [comment] 2023-02-14 06:51
@davideuler This appears to be a bug recently introduced to the method that the reverse proxy servers are using, and not evidence of any misuse of your access token.

About an hour ago, @waylaidwanderer and @PawanOsman started noticing weird responses coming from the hidden completions end point that the reverse proxy is using under the hood. A lot of users have been seeing this unexpectedly for multiple proxy servers – written by different people, so I don't think it's the proxy server's fault.

Your example screenshot is showing a single resposne generated from GPT. It is not showing several responses or prompts from other users or accounts.

With that being said, since the reverse proxy is an undocumented hack, it's completely up to you whether you choose to use it or not. Right now, it's not the default for a reason, because I feel more confident using the official OpenAI completions endpoint.

At least from this example, though, I think we can rule out the malware.

Also, note that `chatgpt-api` package is deprecated; the `chatgpt` package is only one you need.

**Comment by transitive-bullshit** [comment] 2023-02-14 07:15
@davideuler closing for now as I'm fairly confident this is what's going on. Feel free to re-open if you have additional concerns && thank you again for bringing this to my attention.

**Closed by transitive-bullshit** 2023-02-14 07:15 UTC

**Comment by davideuler** [comment] 2023-02-16 03:17
Thanks for the explaination of the case. I will try it again sometime.
